apiVersion: v1
kind: Service
metadata:
  name: spring-argocd-app
spec:
  selector:
    app: spring-argocd-app
  ports:
    - protocol: "TCP"
      port: 9080
      targetPort: 9080
      nodePort: 30009
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: argo-test-app
spec:
  selector:
    matchLabels:
      app: argo-test
  replicas: 1
  template:
    metadata:
      labels:
        app: argo-test-app
    spec:
      containers:
        - name: spring-argocd-app
          image: 21701jake/argo-test:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080