apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-application
  namespace: webservices
spec:
  project: default

  source:
    repoURL: https://github.com/rkrull1956/argoAware
    targetRevision: master
    path: webservice-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: spring-argocd-app

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true