apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: web-service-a
  name: web-service-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-service-a
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: web-service-a
    spec:
      containers:
      - image: 21701jake/web-service-a:latest
        name: webservice-a-api