apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webservice-a
  name: webservice-a
spec:
  replicas: 0
  selector:
    matchLabels:
      app: webservice-a
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webservice-a
    spec:
      containers:
      - image: 21701jake/web-service-a:v2
        name: webservice-a-api
        ports:
          - containerPort: 9080
      imagePullPolicy: Always
