apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: webservice-a
  name: webservice-a
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webservice-a
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: webservice-a
    spec:
      containers:
      - image: 21701jake/web-service-a:latest
        name: webservice-a-api